version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - "c:/Users/l.charles/Desktop/Docker course/fontdend:/app"
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - c:/Users/l.charles/Desktop/Docker course/fontdend:/app
    commd: ["npm","run","test"]